[package]
name = "vercors"
version = "1.0"
lean_version = "leanprover-community/lean:3.33.0"
path = "."

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "e0f7d0e87e8d9a81edd79fec5594aedecd037aaa"}
